version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm build
      - aws s3 sync --delete build/public $S3_BUCKET_FE
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
cache:
  paths:
    - node_modules/**/*
    - public/**/*
    - /usr/local/lib/node_modules/**/*